### ISSUE TITLE
Error when using with New Horizons

### ISSUE THREAD

**Issue by linuxgurugamer** [KSPSnark/PlanetInfoPlus#2]
Just tried starting a new Sandbox game using New Horizons, getting the following error:
`166125 [PlanetInfoPlus] App activated for Kerbin 
166128 Exception handling event onPlanetariumTargetChange in class KnowledgeBase:System.NullReferenceException: Object reference not set to an instance of an object
166129   at PlanetInfoPlus.ExplorationProgress+<>c.<.cctor>b__23_9 (KSPAchievements.CelestialBodySubtree a) [0x00000] in <8c582eff09e948b699e4e53232ab4524>:0 
166130   at PlanetInfoPlus.ExplorationProgress.For (CelestialBody body) [0x00020] in <8c582eff09e948b699e4e53232ab4524>:0 
166131   at PlanetInfoPlus.CelestialBodyExtensions.ExplorationDescription (CelestialBody body) [0x00000] in <8c582eff09e948b699e4e53232ab4524>:0 
166132   at PlanetInfoPlus.PlanetInfoPlus.CreateParam_Exploration (KSP.UI.Screens.KbApp_PlanetParameters app) [0x00000] in <8c582eff09e948b699e4e53232ab4524>:0 
166133   at PlanetInfoPlus.PlanetInfoPlus.CreateGameplayCharacteristics (KSP.UI.Screens.KbApp_PlanetParameters app) [0x000b3] in <8c582eff09e948b699e4e53232ab4524>:0 
166134   at PlanetInfoPlus.PlanetInfoPlus.OnAppActivated (KSP.UI.Screens.KbApp_PlanetParameters app, MapObject target) [0x00139] in <8c582eff09e948b699e4e53232ab4524>:0 
166135   at KSP.UI.Screens.KbApp_PlanetParameters.ActivateApp (MapObject target) [0x00172] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
166136   at KSP.UI.Screens.KnowledgeBase.ActivateApps (KSP.UI.Screens.KnowledgeBase+KbTargetType targetType, MapObject target) [0x000fa] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
166137   at KSP.UI.Screens.KnowledgeBase.OnMapFocusChange (MapObject target) [0x000f4] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
166138   at EventData`1[T].Fire (T data) [0x000b0] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0  
166141 Uploading Crash Report
166142 NullReferenceException: Object reference not set to an instance of an object
166143   at PlanetInfoPlus.ExplorationProgress+<>c.<.cctor>b__23_9 (KSPAchievements.CelestialBodySubtree a) [0x00000] in <8c582eff09e948b699e4e53232ab4524>:0 
166144   at PlanetInfoPlus.ExplorationProgress.For (CelestialBody body) [0x00020] in <8c582eff09e948b699e4e53232ab4524>:0 
166145   at PlanetInfoPlus.CelestialBodyExtensions.ExplorationDescription (CelestialBody body) [0x00000] in <8c582eff09e948b699e4e53232ab4524>:0 
166146   at PlanetInfoPlus.PlanetInfoPlus.CreateParam_Exploration (KSP.UI.Screens.KbApp_PlanetParameters app) [0x00000] in <8c582eff09e948b699e4e53232ab4524>:0 
166147   at PlanetInfoPlus.PlanetInfoPlus.CreateGameplayCharacteristics (KSP.UI.Screens.KbApp_PlanetParameters app) [0x000b3] in <8c582eff09e948b699e4e53232ab4524>:0 
166148   at PlanetInfoPlus.PlanetInfoPlus.OnAppActivated (KSP.UI.Screens.KbApp_PlanetParameters app, MapObject target) [0x00139] in <8c582eff09e948b699e4e53232ab4524>:0 
166149   at KSP.UI.Screens.KbApp_PlanetParameters.ActivateApp (MapObject target) [0x00172] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
166150   at KSP.UI.Screens.KnowledgeBase.ActivateApps (KSP.UI.Screens.KnowledgeBase+KbTargetType targetType, MapObject target) [0x000fa] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
166151   at KSP.UI.Screens.KnowledgeBase.OnMapFocusChange (MapObject target) [0x000f4] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
166152   at EventData`1[T].Fire (T data) [0x000b0] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 `

Full logs, including Player.log, KSP.log, all files in the Logs directory and the ModuleManager.configcache  attached
[PlanetInfo_NH_Logs.zip](https://github.com/KSPSnark/PlanetInfoPlus/files/9003394/PlanetInfo_NH_Logs.zip)

**Comment by linuxgurugamer** [comment]
Just loaded up the KSP Bug Report mod, and uploaded the report here:
https://oshi.at/Qwvv/KSPBugReport_2022-06-28_133214.zip

**Comment by linuxgurugamer** [comment]
If it helps, the error is happening line 80 in ExplorationProgress.cs here:
`                if (candidates[i].achieved.Invoke(progress)) return candidates[i];
`

where i == 2 (which is the Crewed suborbital check)

**Comment by KSPSnark** [comment]
Fixed in PlanetInfoPlus release 1.4.1.  Thanks for the report.
